### ISSUE TITLE
Breadcrumb link error

### ISSUE THREAD

**Issue by ASpiteri-BCGov** [bcgov/CITZ-IMB-SharePoint#15]
## The breadcrumb creates a broken link in certain scenarios.
Example: From list settings click the breadcrumb link for the list's main page.

![image](https://user-images.githubusercontent.com/49036255/57726257-dfbb6f00-7643-11e9-99e3-10654474c836.png)

![image](https://user-images.githubusercontent.com/49036255/57726302-f661c600-7643-11e9-92da-1bd6a2519473.png)

**Comment by SDToews** [comment]
link for lists did not include the web protocol which in turn made it a relative link which SharePoint made weird.  Now fixed
