### ISSUE TITLE
Breadcrumb layout incorrect using OSLO master page

### ISSUE THREAD

**Issue by ASpiteri-BCGov** [bcgov/CITZ-IMB-SharePoint#16]
![image](https://user-images.githubusercontent.com/49036255/57785242-36798500-76e6-11e9-9522-c8ba0a204fd1.png)

**Comment by SDToews** [comment]
SharePoint floats the quick nav in Oslo masterpage.  Added clear fix css and a little bit of top margin to correct.

**Comment by SDToews** [comment]
http://bugs.qp.gov.bc.ca/default.asp?120366

**Comment by SDToews** [comment]
still a problem
