### ISSUE TITLE
Citz SharePoint breadcrumb not displaying correctly

### ISSUE THREAD

**Issue by ASpiteri-BCGov** [bcgov/CITZ-IMB-SharePoint#36]
The SharePoint breadcrumb is not displaying correctly.

Go to the [Here](https://citz.sp.gov.bc.ca/sites/Shared/Project/Refresh/Leads/Lists/WTRP_Exception-Log/AllItems.aspx?View=%7B39145AC2%2D0BD3%2D4CDF%2DA780%2D0BED30C1231F%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence) for an example.

I expected the breadcrumbs to display the correct names not "object object"  

![image](https://user-images.githubusercontent.com/49036255/58486217-48155080-811a-11e9-81c8-c2bb1c7ef0f1.png)

 - OS: Windows 10
 - Browser: IE
 - Version 1.0.0

**Comment by SDToews** [comment]
pull request #38
